services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "${LOCAL_NODE_PORT}:${DOCKER_NODE_PORT}"
    env_file: .env
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:${DOCKER_DB_PORT}/${DB_NAME}"
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /usr/app/node_modules
    networks:
      - docker-network

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${LOCAL_DB_PORT}:${DOCKER_DB_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  postgres-data:
